ci(gh-actions/install-nix): Enable binary substitution fallback
Recently, we noticed both locally and in CI jobs errors like:

    warning: error: unable to download
    'https://blocksense.cachix.org/nar/be9530185b5e3d2f9fab587aa1bde52335bbd60b8e5efb79897a739577fdc482.nar.zst':
    HTTP error 500 response body: Cannot serve NAR; retrying in 517 ms

which, in end the end result in:

    error: some substitutes for the outputs of derivation
    '/nix/store/xpmfjqgr0hdiwf8jiyqr7qs9f4v2r351-cargo-package-eth-keystore-0.5.0.drv'
    failed (usually happens due to networking issues);
    try '--fallback' to build derivation from source

To address this issue globally in the CI, we adjust the nix.conf file generated
by `metacraft-labs/nixos-modules/.github/install-nix` GH action by:

* Enabling fallback for when binary substitution fails
* Reduce the number of retries from 5 to 2
* Set a `connect-timeout` to 30 seconds (before it was unlimited?!)
* Reduce `narinfo-cache-negative-ttl` from 3600 to 120 - allowing CI runners to
  check more often if something built by one machine is now available
  to others (via Cachix)